### ISSUE TITLE
Can't install!

### ISSUE THREAD

**Issue by thearabbit** [kfei/slack-cleaner#54]
Get error
```
root@localhost:~# pip install slack-cleaner
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by sgratzl** [comment]
according to https://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting

you can try to set: `export LC_ALL=C`
