### ISSUE TITLE
slacker.Error message

### ISSUE THREAD

**Issue by philsinatra** [kfei/slack-cleaner#59]
Installed _slack-cleaner_ via _pip_ without an issue. Goal is to remove all files in the account, however when running the command I get the following feedback:

```bash
$ sudo slack-cleaner --token SECRET --file --user "*" --rate=1
Running slack-cleaner v0.3.0
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 7, in <module>
    from slack_cleaner.cli import main
  File "/Library/Python/2.7/site-packages/slack_cleaner/cli.py", line 61, in <module>
    init_user_dict()
  File "/Library/Python/2.7/site-packages/slack_cleaner/cli.py", line 52, in init_user_dict
    res = slack.users.list().body
  File "/Library/Python/2.7/site-packages/slacker/__init__.py", line 164, in list
    return self.get('users.list', params={'presence': int(presence)})
  File "/Library/Python/2.7/site-packages/slacker/__init__.py", line 90, in get
    api, **kwargs
  File "/Library/Python/2.7/site-packages/slacker/__init__.py", line 72, in _request
    raise Error(response.error)
slacker.Error: invalid_auth

**Comment by onhernandes** [comment]
+1

**Comment by sgratzl** [comment]
how did you create the secret token?

**Comment by jtagcat** [comment]
Same issue. URL `https://api.slack.com/apps/<redacted>/oauth?success=1`

![image](https://user-images.githubusercontent.com/38327267/119491489-7f408b80-bd4d-11eb-996d-ba66689094a4.png)

![image](https://user-images.githubusercontent.com/38327267/119491635-aac37600-bd4d-11eb-8a29-712875b18401.png)


Added both user and bot scopes as a troubleshooting step. Tried both bot and user tokens, and with, without `--bot`.
