### ISSUE TITLE
slackbot problem

### ISSUE THREAD

**Issue by breezzz** [kfei/slack-cleaner#63]
Display name: slackbot, member ID: USLACKBOT
slack-cleaner --token=[token]  --file --user uslackbot
slack-cleaner --token=[token]  --file --user slackbot
slack-cleaner --token=[token]  --message --direct slackbot --bot
slack-cleaner --token=[token]  --message --direct uslackbot --bot
```
Running slack-cleaner v0.3.0
Traceback (most recent call last):
  File "/usr/local/bin/slack-cleaner", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/slack_cleaner/cli.py", line 337, in main
    message_cleaner()
  File "/usr/local/lib/python3.6/site-packages/slack_cleaner/cli.py", line 286, in message_cleaner
    _channel_id = get_direct_id_by_name(args.direct_name)
  File "/usr/local/lib/python3.6/site-packages/slack_cleaner/cli.py", line 244, in get_direct_id_by_name
    _user_id = get_user_id_by_name(name)
  File "/usr/local/lib/python3.6/site-packages/slack_cleaner/cli.py", line 224, in get_user_id_by_name
    for k, v in user_dict.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

**Comment by sgratzl** [comment]
this version doesn't work with python3. you can take a look at https://github.com/sgratzl/slack-cleaner
